import type { MenuItem, Order } from "./types"

export const mockMenuItems: MenuItem[] = [
  // Salatlar (Appetizers/Salads)
  {
    id: "1",
    name: "Achichiq salat",
    description: "Yangi pomidor, bodring, piyoz va ko'katlar bilan",
    price: 25000,
    category: "appetizers",
    image_url: "/fresh-uzbek-achichuk-tomato-cucumber-onion-salad.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "2",
    name: "Olivye salati",
    description: "An'anaviy rus salati kartoshka va mayonez bilan",
    price: 35000,
    category: "appetizers",
    image_url: "/russian-olivier-salad-with-potatoes-and-mayonnaise.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "3",
    name: "Tuzlangan sabzavotlar",
    description: "Uy sharoitida tayyorlangan tuzlangan bodring va pomidor",
    price: 20000,
    category: "appetizers",
    image_url: "/pickled-vegetables-cucumbers-tomatoes.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  // Asosiy taomlar (Main dishes)
  {
    id: "4",
    name: "Palov",
    description: "An'anaviy o'zbek palovi mol go'shti, sabzi va ziravorlar bilan",
    price: 45000,
    category: "main",
    image_url: "/uzbek-plov-rice-pilaf-with-beef-carrots-and-spices.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "5",
    name: "Lag'mon",
    description: "Qo'lda tortilgan uzun makaronga mol go'shti va sabzavotlar",
    price: 42000,
    category: "main",
    image_url: "/lagman-noodle-soup-with-beef-and-vegetables.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "6",
    name: "Manti",
    description: "Bug'da pishirilgan katta chuchvara mol go'shti va piyoz bilan",
    price: 38000,
    category: "main",
    image_url: "/uzbek-manti-steamed-dumplings-with-beef.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "7",
    name: "Chuchvara",
    description: "Kichik chuchvara sho'rva ichida yoki qaymoq bilan",
    price: 35000,
    category: "main",
    image_url: "/uzbek-chuchvara-small-dumplings-in-broth.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  // Sho'rvalar (Soups)
  {
    id: "8",
    name: "Mastava",
    description: "Guruch va sabzavotli go'shtli sho'rva",
    price: 32000,
    category: "soups",
    image_url: "/uzbek-mastava-rice-soup-with-meat-and-vegetables.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "9",
    name: "Sho'rva",
    description: "An'anaviy qo'y go'shti sho'rvasi kartoshka bilan",
    price: 35000,
    category: "soups",
    image_url: "/uzbek-shorva-lamb-soup-with-potatoes.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  // Kaboblar (Grilled)
  {
    id: "10",
    name: "Qo'y kabob",
    description: "Ko'mirda pishirilgan yumshoq qo'y go'shti",
    price: 55000,
    category: "grilled",
    image_url: "/grilled-lamb-shashlik-kebab-on-skewers.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "11",
    name: "Tovuq kabob",
    description: "Ziravorli marinadda tovuq kabob",
    price: 35000,
    category: "grilled",
    image_url: "/grilled-chicken-shashlik-kebab-marinated.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "12",
    name: "Lyulya kabob",
    description: "Maydalangan mol go'shtidan tayyorlangan kabob",
    price: 45000,
    category: "grilled",
    image_url: "/lyulya-kebab-minced-meat-grilled.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  // Ichimliklar (Drinks)
  {
    id: "13",
    name: "Yashil choy",
    description: "An'anaviy o'zbek yashil choyi",
    price: 8000,
    category: "drinks",
    image_url: "/uzbek-green-tea-in-traditional-teapot.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "14",
    name: "Qora choy",
    description: "Xushbo'y qora choy",
    price: 8000,
    category: "drinks",
    image_url: "/black-tea-in-glass-cup.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "15",
    name: "Kompot",
    description: "Uy sharoitida tayyorlangan mevali ichimlik",
    price: 12000,
    category: "drinks",
    image_url: "/homemade-fruit-kompot-drink.jpg",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "16",
    name: "Ayron",
    description: "Sovuq sut ichimlik",
    price: 10000,
    category: "drinks",
    image_url: "/placeholder.svg?height=300&width=400",
    available_on_mobile: true,
    available_on_website: true,
  },
  // Shirinliklar (Desserts)
  {
    id: "17",
    name: "Halvo",
    description: "An'anaviy o'zbek halvosi",
    price: 18000,
    category: "desserts",
    image_url: "/placeholder.svg?height=300&width=400",
    available_on_mobile: true,
    available_on_website: true,
  },
  {
    id: "18",
    name: "Chak-chak",
    description: "Asalli shirinlik",
    price: 22000,
    category: "desserts",
    image_url: "/placeholder.svg?height=300&width=400",
    available_on_mobile: true,
    available_on_website: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    customer_name: "Aziz Karimov",
    customer_phone: "+998901234567",
    mode: "delivery",
    delivery_address: "Yunusobod tumani, 12-uy",
    delivery_distance: 4.5,
    items: [
      { ...mockMenuItems[3], quantity: 2 },
      { ...mockMenuItems[12], quantity: 1 },
    ],
    subtotal: 98000,
    delivery_fee: 7500,
    total: 105500,
    status: "preparing",
    source: "website",
    payment_method: "cash",
  },
  {
    id: "ORD-002",
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    customer_name: "Malika Rahimova",
    customer_phone: "+998909876543",
    mode: "dine-in",
    table_number: "5",
    items: [
      { ...mockMenuItems[9], quantity: 3 },
      { ...mockMenuItems[0], quantity: 2 },
      { ...mockMenuItems[13], quantity: 3 },
    ],
    subtotal: 239000,
    delivery_fee: 0,
    total: 239000,
    status: "new",
    source: "website",
    payment_method: "card",
  },
  {
    id: "ORD-003",
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    customer_name: "Bobur Toshmatov",
    customer_phone: "+998933456789",
    mode: "delivery",
    delivery_address: "Mirzo Ulug'bek tumani, 45-uy",
    delivery_distance: 2.1,
    items: [
      { ...mockMenuItems[4], quantity: 2 },
      { ...mockMenuItems[7], quantity: 1 },
    ],
    subtotal: 116000,
    delivery_fee: 0,
    total: 116000,
    status: "ready",
    source: "call-center",
    payment_method: "click",
  },
]
